name: build-latex
run-name: Build LaTeX
on:
  push:
    branches:
      - primary

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: xu-cheng/latex-action@v2
        with:
          root_file: src/document.tex
          work_in_root_file_dir: true

      - name: move to build directory
        run: |
          mkdir dist
          cp src/document.pdf pages/document.pdf

      - name: deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}